// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adb_config_demo.proto

package com.erobbing.adb_config_demo;

public final class AdbConfigDemo {
    private AdbConfigDemo() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code com.erobbing.adb_config_demo.ErrorCode}
     */
    public enum ErrorCode
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>OK = 0;</code>
         */
        OK(0),
        /**
         * <code>COMMON_ERROR = 1;</code>
         */
        COMMON_ERROR(1),
        /**
         * <code>UNKNOWN_CMD = 100;</code>
         */
        UNKNOWN_CMD(100),
        UNRECOGNIZED(-1),;

        /**
         * <code>OK = 0;</code>
         */
        public static final int OK_VALUE = 0;
        /**
         * <code>COMMON_ERROR = 1;</code>
         */
        public static final int COMMON_ERROR_VALUE = 1;
        /**
         * <code>UNKNOWN_CMD = 100;</code>
         */
        public static final int UNKNOWN_CMD_VALUE = 100;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ErrorCode valueOf(int value) {
            return forNumber(value);
        }

        public static ErrorCode forNumber(int value) {
            switch (value) {
                case 0:
                    return OK;
                case 1:
                    return COMMON_ERROR;
                case 100:
                    return UNKNOWN_CMD;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                ErrorCode> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
                    public ErrorCode findValueByNumber(int number) {
                        return ErrorCode.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.erobbing.adb_config_demo.AdbConfigDemo.getDescriptor().getEnumTypes().get(0);
        }

        private static final ErrorCode[] VALUES = values();

        public static ErrorCode valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private ErrorCode(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.erobbing.adb_config_demo.ErrorCode)
    }

    /**
     * Protobuf enum {@code com.erobbing.adb_config_demo.Cmd}
     */
    public enum Cmd
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>cmd_dummy = 0;</code>
         */
        cmd_dummy(0),
        /**
         * <pre>
         * 从设备端获取设置
         * </pre>
         * <p>
         * <code>cmdReadConfig = 1;</code>
         */
        cmdReadConfig(1),
        /**
         * <pre>
         * 保存设置到设备端
         * </pre>
         * <p>
         * <code>cmdWriteConfig = 2;</code>
         */
        cmdWriteConfig(2),
        /**
         * <pre>
         * 箱注册
         * </pre>
         * <p>
         * <code>cmdRegisterBox = 3;</code>
         */
        cmdRegisterBox(3),
        /**
         * <pre>
         * 箱注销
         * </pre>
         * <p>
         * <code>cmdUnregisterBox = 4;</code>
         */
        cmdUnregisterBox(4),
        /**
         * <pre>
         * 扣注销
         * </pre>
         * <p>
         * <code>cmdUnregisterKey = 5;</code>
         */
        cmdUnregisterKey(5),
        UNRECOGNIZED(-1),;

        /**
         * <code>cmd_dummy = 0;</code>
         */
        public static final int cmd_dummy_VALUE = 0;
        /**
         * <pre>
         * 从设备端获取设置
         * </pre>
         * <p>
         * <code>cmdReadConfig = 1;</code>
         */
        public static final int cmdReadConfig_VALUE = 1;
        /**
         * <pre>
         * 保存设置到设备端
         * </pre>
         * <p>
         * <code>cmdWriteConfig = 2;</code>
         */
        public static final int cmdWriteConfig_VALUE = 2;
        /**
         * <pre>
         * 箱注册
         * </pre>
         * <p>
         * <code>cmdRegisterBox = 3;</code>
         */
        public static final int cmdRegisterBox_VALUE = 3;
        /**
         * <pre>
         * 箱注销
         * </pre>
         * <p>
         * <code>cmdUnregisterBox = 4;</code>
         */
        public static final int cmdUnregisterBox_VALUE = 4;
        /**
         * <pre>
         * 扣注销
         * </pre>
         * <p>
         * <code>cmdUnregisterKey = 5;</code>
         */
        public static final int cmdUnregisterKey_VALUE = 5;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static Cmd valueOf(int value) {
            return forNumber(value);
        }

        public static Cmd forNumber(int value) {
            switch (value) {
                case 0:
                    return cmd_dummy;
                case 1:
                    return cmdReadConfig;
                case 2:
                    return cmdWriteConfig;
                case 3:
                    return cmdRegisterBox;
                case 4:
                    return cmdUnregisterBox;
                case 5:
                    return cmdUnregisterKey;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Cmd>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                Cmd> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<Cmd>() {
                    public Cmd findValueByNumber(int number) {
                        return Cmd.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.erobbing.adb_config_demo.AdbConfigDemo.getDescriptor().getEnumTypes().get(1);
        }

        private static final Cmd[] VALUES = values();

        public static Cmd valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private Cmd(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.erobbing.adb_config_demo.Cmd)
    }

    public interface ConfigOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.erobbing.adb_config_demo.Config)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 0: OK; 其他值：错误码
         * </pre>
         * <p>
         * <code>int32 errorCode = 1;</code>
         */
        int getErrorCode();

        /**
         * <pre>
         * 箱ID
         * </pre>
         * <p>
         * <code>string boxID = 2;</code>
         */
        java.lang.String getBoxID();

        /**
         * <pre>
         * 箱ID
         * </pre>
         * <p>
         * <code>string boxID = 2;</code>
         */
        com.google.protobuf.ByteString
        getBoxIDBytes();

        /**
         * <pre>
         * 钥匙扣ID
         * </pre>
         * <p>
         * <code>string keyID = 3;</code>
         */
        java.lang.String getKeyID();

        /**
         * <pre>
         * 钥匙扣ID
         * </pre>
         * <p>
         * <code>string keyID = 3;</code>
         */
        com.google.protobuf.ByteString
        getKeyIDBytes();

        /**
         * <pre>
         * 店ID
         * </pre>
         * <p>
         * <code>string shopID = 4;</code>
         */
        java.lang.String getShopID();

        /**
         * <pre>
         * 店ID
         * </pre>
         * <p>
         * <code>string shopID = 4;</code>
         */
        com.google.protobuf.ByteString
        getShopIDBytes();

        /**
         * <pre>
         * 箱是否注册
         * </pre>
         * <p>
         * <code>bool boxRegisted = 5;</code>
         */
        boolean getBoxRegisted();
    }

    /**
     * <pre>
     * 每个通讯的数据内容，根据需要获取或设置某(几)个参数值
     * </pre>
     * <p>
     * Protobuf type {@code com.erobbing.adb_config_demo.Config}
     */
    public static final class Config extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.erobbing.adb_config_demo.Config)
            ConfigOrBuilder {
        // Use Config.newBuilder() to construct.
        private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Config() {
            errorCode_ = 0;
            boxID_ = "";
            keyID_ = "";
            shopID_ = "";
            boxRegisted_ = false;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Config(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            errorCode_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            boxID_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            keyID_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            shopID_ = s;
                            break;
                        }
                        case 40: {

                            boxRegisted_ = input.readBool();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.erobbing.adb_config_demo.AdbConfigDemo.internal_static_com_erobbing_adb_config_demo_Config_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.erobbing.adb_config_demo.AdbConfigDemo.internal_static_com_erobbing_adb_config_demo_Config_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.erobbing.adb_config_demo.AdbConfigDemo.Config.class, com.erobbing.adb_config_demo.AdbConfigDemo.Config.Builder.class);
        }

        public static final int ERRORCODE_FIELD_NUMBER = 1;
        private int errorCode_;

        /**
         * <pre>
         * 0: OK; 其他值：错误码
         * </pre>
         * <p>
         * <code>int32 errorCode = 1;</code>
         */
        public int getErrorCode() {
            return errorCode_;
        }

        public static final int BOXID_FIELD_NUMBER = 2;
        private volatile java.lang.Object boxID_;

        /**
         * <pre>
         * 箱ID
         * </pre>
         * <p>
         * <code>string boxID = 2;</code>
         */
        public java.lang.String getBoxID() {
            java.lang.Object ref = boxID_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                boxID_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 箱ID
         * </pre>
         * <p>
         * <code>string boxID = 2;</code>
         */
        public com.google.protobuf.ByteString
        getBoxIDBytes() {
            java.lang.Object ref = boxID_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                boxID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int KEYID_FIELD_NUMBER = 3;
        private volatile java.lang.Object keyID_;

        /**
         * <pre>
         * 钥匙扣ID
         * </pre>
         * <p>
         * <code>string keyID = 3;</code>
         */
        public java.lang.String getKeyID() {
            java.lang.Object ref = keyID_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                keyID_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 钥匙扣ID
         * </pre>
         * <p>
         * <code>string keyID = 3;</code>
         */
        public com.google.protobuf.ByteString
        getKeyIDBytes() {
            java.lang.Object ref = keyID_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                keyID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SHOPID_FIELD_NUMBER = 4;
        private volatile java.lang.Object shopID_;

        /**
         * <pre>
         * 店ID
         * </pre>
         * <p>
         * <code>string shopID = 4;</code>
         */
        public java.lang.String getShopID() {
            java.lang.Object ref = shopID_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                shopID_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 店ID
         * </pre>
         * <p>
         * <code>string shopID = 4;</code>
         */
        public com.google.protobuf.ByteString
        getShopIDBytes() {
            java.lang.Object ref = shopID_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                shopID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BOXREGISTED_FIELD_NUMBER = 5;
        private boolean boxRegisted_;

        /**
         * <pre>
         * 箱是否注册
         * </pre>
         * <p>
         * <code>bool boxRegisted = 5;</code>
         */
        public boolean getBoxRegisted() {
            return boxRegisted_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (errorCode_ != 0) {
                output.writeInt32(1, errorCode_);
            }
            if (!getBoxIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, boxID_);
            }
            if (!getKeyIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, keyID_);
            }
            if (!getShopIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, shopID_);
            }
            if (boxRegisted_ != false) {
                output.writeBool(5, boxRegisted_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (errorCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, errorCode_);
            }
            if (!getBoxIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, boxID_);
            }
            if (!getKeyIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, keyID_);
            }
            if (!getShopIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, shopID_);
            }
            if (boxRegisted_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(5, boxRegisted_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.erobbing.adb_config_demo.AdbConfigDemo.Config)) {
                return super.equals(obj);
            }
            com.erobbing.adb_config_demo.AdbConfigDemo.Config other = (com.erobbing.adb_config_demo.AdbConfigDemo.Config) obj;

            boolean result = true;
            result = result && (getErrorCode()
                    == other.getErrorCode());
            result = result && getBoxID()
                    .equals(other.getBoxID());
            result = result && getKeyID()
                    .equals(other.getKeyID());
            result = result && getShopID()
                    .equals(other.getShopID());
            result = result && (getBoxRegisted()
                    == other.getBoxRegisted());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
            hash = (53 * hash) + getErrorCode();
            hash = (37 * hash) + BOXID_FIELD_NUMBER;
            hash = (53 * hash) + getBoxID().hashCode();
            hash = (37 * hash) + KEYID_FIELD_NUMBER;
            hash = (53 * hash) + getKeyID().hashCode();
            hash = (37 * hash) + SHOPID_FIELD_NUMBER;
            hash = (53 * hash) + getShopID().hashCode();
            hash = (37 * hash) + BOXREGISTED_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getBoxRegisted());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.erobbing.adb_config_demo.AdbConfigDemo.Config prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 每个通讯的数据内容，根据需要获取或设置某(几)个参数值
         * </pre>
         * <p>
         * Protobuf type {@code com.erobbing.adb_config_demo.Config}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.erobbing.adb_config_demo.Config)
                com.erobbing.adb_config_demo.AdbConfigDemo.ConfigOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.erobbing.adb_config_demo.AdbConfigDemo.internal_static_com_erobbing_adb_config_demo_Config_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.erobbing.adb_config_demo.AdbConfigDemo.internal_static_com_erobbing_adb_config_demo_Config_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.erobbing.adb_config_demo.AdbConfigDemo.Config.class, com.erobbing.adb_config_demo.AdbConfigDemo.Config.Builder.class);
            }

            // Construct using com.erobbing.adb_config_demo.AdbConfigDemo.Config.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                errorCode_ = 0;

                boxID_ = "";

                keyID_ = "";

                shopID_ = "";

                boxRegisted_ = false;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.erobbing.adb_config_demo.AdbConfigDemo.internal_static_com_erobbing_adb_config_demo_Config_descriptor;
            }

            public com.erobbing.adb_config_demo.AdbConfigDemo.Config getDefaultInstanceForType() {
                return com.erobbing.adb_config_demo.AdbConfigDemo.Config.getDefaultInstance();
            }

            public com.erobbing.adb_config_demo.AdbConfigDemo.Config build() {
                com.erobbing.adb_config_demo.AdbConfigDemo.Config result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.erobbing.adb_config_demo.AdbConfigDemo.Config buildPartial() {
                com.erobbing.adb_config_demo.AdbConfigDemo.Config result = new com.erobbing.adb_config_demo.AdbConfigDemo.Config(this);
                result.errorCode_ = errorCode_;
                result.boxID_ = boxID_;
                result.keyID_ = keyID_;
                result.shopID_ = shopID_;
                result.boxRegisted_ = boxRegisted_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.erobbing.adb_config_demo.AdbConfigDemo.Config) {
                    return mergeFrom((com.erobbing.adb_config_demo.AdbConfigDemo.Config) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.erobbing.adb_config_demo.AdbConfigDemo.Config other) {
                if (other == com.erobbing.adb_config_demo.AdbConfigDemo.Config.getDefaultInstance())
                    return this;
                if (other.getErrorCode() != 0) {
                    setErrorCode(other.getErrorCode());
                }
                if (!other.getBoxID().isEmpty()) {
                    boxID_ = other.boxID_;
                    onChanged();
                }
                if (!other.getKeyID().isEmpty()) {
                    keyID_ = other.keyID_;
                    onChanged();
                }
                if (!other.getShopID().isEmpty()) {
                    shopID_ = other.shopID_;
                    onChanged();
                }
                if (other.getBoxRegisted() != false) {
                    setBoxRegisted(other.getBoxRegisted());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.erobbing.adb_config_demo.AdbConfigDemo.Config parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.erobbing.adb_config_demo.AdbConfigDemo.Config) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int errorCode_;

            /**
             * <pre>
             * 0: OK; 其他值：错误码
             * </pre>
             * <p>
             * <code>int32 errorCode = 1;</code>
             */
            public int getErrorCode() {
                return errorCode_;
            }

            /**
             * <pre>
             * 0: OK; 其他值：错误码
             * </pre>
             * <p>
             * <code>int32 errorCode = 1;</code>
             */
            public Builder setErrorCode(int value) {

                errorCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 0: OK; 其他值：错误码
             * </pre>
             * <p>
             * <code>int32 errorCode = 1;</code>
             */
            public Builder clearErrorCode() {

                errorCode_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object boxID_ = "";

            /**
             * <pre>
             * 箱ID
             * </pre>
             * <p>
             * <code>string boxID = 2;</code>
             */
            public java.lang.String getBoxID() {
                java.lang.Object ref = boxID_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    boxID_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 箱ID
             * </pre>
             * <p>
             * <code>string boxID = 2;</code>
             */
            public com.google.protobuf.ByteString
            getBoxIDBytes() {
                java.lang.Object ref = boxID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    boxID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 箱ID
             * </pre>
             * <p>
             * <code>string boxID = 2;</code>
             */
            public Builder setBoxID(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                boxID_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 箱ID
             * </pre>
             * <p>
             * <code>string boxID = 2;</code>
             */
            public Builder clearBoxID() {

                boxID_ = getDefaultInstance().getBoxID();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 箱ID
             * </pre>
             * <p>
             * <code>string boxID = 2;</code>
             */
            public Builder setBoxIDBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                boxID_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object keyID_ = "";

            /**
             * <pre>
             * 钥匙扣ID
             * </pre>
             * <p>
             * <code>string keyID = 3;</code>
             */
            public java.lang.String getKeyID() {
                java.lang.Object ref = keyID_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    keyID_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 钥匙扣ID
             * </pre>
             * <p>
             * <code>string keyID = 3;</code>
             */
            public com.google.protobuf.ByteString
            getKeyIDBytes() {
                java.lang.Object ref = keyID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    keyID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 钥匙扣ID
             * </pre>
             * <p>
             * <code>string keyID = 3;</code>
             */
            public Builder setKeyID(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                keyID_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 钥匙扣ID
             * </pre>
             * <p>
             * <code>string keyID = 3;</code>
             */
            public Builder clearKeyID() {

                keyID_ = getDefaultInstance().getKeyID();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 钥匙扣ID
             * </pre>
             * <p>
             * <code>string keyID = 3;</code>
             */
            public Builder setKeyIDBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                keyID_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object shopID_ = "";

            /**
             * <pre>
             * 店ID
             * </pre>
             * <p>
             * <code>string shopID = 4;</code>
             */
            public java.lang.String getShopID() {
                java.lang.Object ref = shopID_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    shopID_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 店ID
             * </pre>
             * <p>
             * <code>string shopID = 4;</code>
             */
            public com.google.protobuf.ByteString
            getShopIDBytes() {
                java.lang.Object ref = shopID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    shopID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 店ID
             * </pre>
             * <p>
             * <code>string shopID = 4;</code>
             */
            public Builder setShopID(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                shopID_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 店ID
             * </pre>
             * <p>
             * <code>string shopID = 4;</code>
             */
            public Builder clearShopID() {

                shopID_ = getDefaultInstance().getShopID();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 店ID
             * </pre>
             * <p>
             * <code>string shopID = 4;</code>
             */
            public Builder setShopIDBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                shopID_ = value;
                onChanged();
                return this;
            }

            private boolean boxRegisted_;

            /**
             * <pre>
             * 箱是否注册
             * </pre>
             * <p>
             * <code>bool boxRegisted = 5;</code>
             */
            public boolean getBoxRegisted() {
                return boxRegisted_;
            }

            /**
             * <pre>
             * 箱是否注册
             * </pre>
             * <p>
             * <code>bool boxRegisted = 5;</code>
             */
            public Builder setBoxRegisted(boolean value) {

                boxRegisted_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 箱是否注册
             * </pre>
             * <p>
             * <code>bool boxRegisted = 5;</code>
             */
            public Builder clearBoxRegisted() {

                boxRegisted_ = false;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.erobbing.adb_config_demo.Config)
        }

        // @@protoc_insertion_point(class_scope:com.erobbing.adb_config_demo.Config)
        private static final com.erobbing.adb_config_demo.AdbConfigDemo.Config DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.erobbing.adb_config_demo.AdbConfigDemo.Config();
        }

        public static com.erobbing.adb_config_demo.AdbConfigDemo.Config getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Config>
                PARSER = new com.google.protobuf.AbstractParser<Config>() {
            public Config parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Config(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Config> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Config> getParserForType() {
            return PARSER;
        }

        public com.erobbing.adb_config_demo.AdbConfigDemo.Config getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_erobbing_adb_config_demo_Config_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_erobbing_adb_config_demo_Config_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\025adb_config_demo.proto\022\034com.erobbing.ad" +
                        "b_config_demo\"^\n\006Config\022\021\n\terrorCode\030\001 \001" +
                        "(\005\022\r\n\005boxID\030\002 \001(\t\022\r\n\005keyID\030\003 \001(\t\022\016\n\006shop" +
                        "ID\030\004 \001(\t\022\023\n\013boxRegisted\030\005 \001(\010*6\n\tErrorCo" +
                        "de\022\006\n\002OK\020\000\022\020\n\014COMMON_ERROR\020\001\022\017\n\013UNKNOWN_" +
                        "CMD\020d*{\n\003Cmd\022\r\n\tcmd_dummy\020\000\022\021\n\rcmdReadCo" +
                        "nfig\020\001\022\022\n\016cmdWriteConfig\020\002\022\022\n\016cmdRegiste" +
                        "rBox\020\003\022\024\n\020cmdUnregisterBox\020\004\022\024\n\020cmdUnreg" +
                        "isterKey\020\005b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_com_erobbing_adb_config_demo_Config_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_erobbing_adb_config_demo_Config_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_erobbing_adb_config_demo_Config_descriptor,
                new java.lang.String[]{"ErrorCode", "BoxID", "KeyID", "ShopID", "BoxRegisted",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
